-- COQ configs, this has to be done before excution of coq
vim.g.coq_settings = {
  auto_start = "shut-up",
  ["keymap.recommended"] = false,
  ["keymap.jump_to_mark"] = "<s-tab>",
  ["keymap.manual_complete"] = "<c-n>",
  ["keymap.repeat"] = ".",
  ["clients.tabnine.enabled"] = true,
  ["display.icons.mappings"] = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "ﰠ",
    Variable = "",
    Class = "ﴯ",
    Interface = "",
    Module = "",
    Property = "ﰠ",
    Unit = "塞",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "פּ",
    Event = "",
    Operator = "",
    TypeParameter = ""
  }
}
