#! /bin/sh

# Dependencies
# sudo pacman -S bspwm sxhkd dunst arandr picom nitrogen polybar pavucontrol lxappearance-gtk3 bitwarden-cli bwmenu xorg-xsetroot

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# sxhkd (mappings)
pgrep -x sxhkd > /dev/null || sxhkd &

# Notifications
dunst --config $HOME/.config/dunst/dunstrc &

# Wallpaper run the application from the first time to configure the wallpaper
nitrogen --restore &

# Autostart picom (cool fadding elements, and transparency)
picom --config $HOME/.config/picom/picom.conf &

# For pamac to work authentification GUI prompt
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# auto start polybar
sh $HOME/.config/polybar/launch.sh --bspwm

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

# You can view the CLASS_NAME that it is asign to the window by doing the command 'xprop'
# And clicking the window that you need the value from
bspc rule -a Brave-browser desktop='^1'
bspc rule -a discord desktop='^6'
bspc rule -a Lxappearance desktop='^6' state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Pavucontrol state=floating

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d I II III IV V VI VII VIII

bspc config window_gap 10
bspc config border_width 3
bspc config top_padding 30
bspc config left_padding 1
bspc config right_padding 1
bspc config bottom_padding 1

bspc config gapless_monocle false
bspc config single_monocle true
bspc config borderless_monocle true
bspc config paddingless_monocle false

# ##############################################################################
# #                            COLORS CONFIGURATION                            #
# ##############################################################################

