# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/fredo/.oh-my-zsh"

# ZSH theme
ZSH_THEME="fredo"

# Base16 Shell colorscheme
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# FZF fuzzy finder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(
    git
    tmux
    vi-mode
    fzf
    colored-man-pages
)

source $ZSH/oh-my-zsh.sh

#
# User configuration
#

# Some defaults
export EDITOR='vim'
export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export TERM=xterm-256color

# Change colors of ow= other writable, tw= sticky writable on terminal
export LS_COLORS="$LS_COLORS:ow=1;4;34:tw=1;4;34:"

# Specifics
# export ARCHFLAGS="-arch x86_64"

# Change between modes more quickly
export KEYTIMEOUT=1

source $HOME/.bash_aliases

# Use vim keys in tab complete menu
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Make CTRL-Z background things and unbackground them.
function fg-bg() {
    if [[ $#BUFFER -eq 0  ]]; then
        fg
    else
        zle push-input
    fi
}

zle -N fg-bg
bindkey '^Z' fg-bg

# FZF configuration
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

_gen_fzf_default_opts() {
    local color00='#181818'
    local color01='#282828'
    local color02='#383838'
    local color03='#585858'
    local color04='#b8b8b8'
    local color05='#d8d8d8'
    local color06='#e8e8e8'
    local color07='#f8f8f8'
    local color08='#ab4642'
    local color09='#dc9656'
    local color0A='#f7ca88'
    local color0B='#a1b56c'
    local color0C='#86c1b9'
    local color0D='#7cafc2'
    local color0E='#ba8baf'
    local color0F='#a16946'

    export FZF_DEFAULT_OPTS="
    --color=bg+:$color01,bg:$color00,spinner:$color0C,hl:$color08
    --color=fg:$color04,header:$color0D,info:$color0A,pointer:$color0C
    --color=marker:$color0C,fg+:$color06,prompt:$color0A,hl+:$color08
    --no-mouse
    "
}
_gen_fzf_default_opts
