# Own aliases

# Important folders
alias doc='cd ~/Documents && la'
alias dow='cd ~/Downloads && la'
alias dot='cd ~/dotfiles && la'
alias fredo='cd ~/Documents/Fredo && la'

# Education folders
alias j='cd ~/Documents/Universidad/Javeriana/ && la'
alias j3='cd ~/Documents/Universidad/Javeriana/TercerSemestre && la'
alias j3e='cd ~/Documents/Universidad/Javeriana/TercerSemestre/ED/ && la'
alias j4='cd ~/Documents/Universidad/Javeriana/CuartoSemestre && la'
alias j4p='cd ~/Documents/Universidad/Javeriana/CuartoSemestre/POO && la'

# Quick changes
alias vc='vim ~/.vimrc'
alias vp='vim ~/.config/polybar/config'
alias vi3='vim ~/.config/i3/config'
alias vb='vim ~/.bashrc'
alias vba="vim ~/.bash_aliases"
alias :q='exit'
alias v='vim'

# Open any file from terminal (Need Ranger)
alias open='rifle 2>/dev/null'

# Tmux aliases
alias t='tmux'

