#
# Own aliases
#

# Most used
alias ..='cd ..'
alias ...='cd ../..'
alias doc='cd ~/Documents'
alias dot='cd ~/dotfiles'
alias dow='cd ~/Downloads'
alias usb='cd /run/media/$(whoami)/'
alias :q='exit'

# Quick config changes alias vb='vim ~/.bashrc'
alias vba="vim ~/.bash_aliases"
alias vz='vim ~/.zshrc'
alias vt='vim ~/.tmux.conf'
alias vi3='vim ~/.i3/config'

# Vim/neovim aliases
if command -v nvim &> /dev/null
then
  alias vim='nvim'
  alias vc='cd ~/.config/nvim && vim init.lua'
elif command -v vim &> /dev/null
then
  alias vc='cd ~/.vim && vim ~/.vimrc'
fi

# Alacritty config alias
if command -v alacritty &> /dev/null
then
  alias va='vim ~/.config/alacritty/alacritty.yml'
fi
